serviceName: airflow
owner: data-engineering

service:
  logGroupName: airflow/ecs/fargate
  cidrBlock: 10.0.0.0
  baseUrl: http://localhost:8080
  port: 80
  imageVersion: latest
  flower:
    cpu: 512
    memory: 1024
    port: 5555
  scheduler:
    cpu: 1024
    memory: 2048
  webserver:
    port: 8080
    cpu: 1024
    memory: 2048
  workers:
    port: 8793
    cpu: 1024
    memory: 2048

publicSubnet:
  1:
    cidrBlock: 10.0.1.0/24
    availabilityZone: a
  2:
    cidrBlock: 10.0.2.0/24
    availabilityZone: b
  3:
    cidrBlock: 10.0.3.0/24
    availabilityZone: c

metadataDb:
  instanceType: db.t3.micro
  port: 5432
  dbName: airflow
  engine: aurora-postgresql
  engineMode: provisioned
  engineVersion: 11.7
  family: aurora-postgresql11
  deletionProtection: false
  enableHttpEndpoint: true
  storageEncrypted: true
  enableIAMDatabaseAuthentication: true
  secrets:
    rotationScheduleDays: 30
  parameters:
    maxConnections: 100


celeryBackend:
  port: 6379
  azMode: single-az
  engine: redis
  engineVersion: 4.0.10
  autoMinorVersionUpgrade: true
  instanceType: cache.t3.small
  numNodes: 1

ecr:
  imagesLifecycleCount: 10

cloudwatch:
  ecsLogGroup:
    retention: 14
